//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperAdventure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperAdventure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You drink a .
        /// </summary>
        internal static string SuperAdventure_btnUsePotion_Click_You_drink_a_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUsePotion_Click_You_drink_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  did .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click__did_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click__did_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click__for_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click__for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  killed you..
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click__killed_you_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click__killed_you_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points..
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click__points_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click__points_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points of damage..
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click__points_of_damage_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click__points_of_damage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click_The_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click_The_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You defeated the .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click_You_defeated_the_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click_You_defeated_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hit the .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click_You_hit_the_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click_You_hit_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You loot .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click_You_loot_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click_You_loot_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive .
        /// </summary>
        internal static string SuperAdventure_btnUseWeapon_Click_You_receive_ {
            get {
                return ResourceManager.GetString("SuperAdventure_btnUseWeapon_Click_You_receive_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_East {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience:.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Experience_ {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Experience_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold:.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Gold_ {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Gold_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Points:.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Hit_Points_ {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Hit_Points_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Level_ {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Level_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_North {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Select_Action {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Select_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_South {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_Use {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string SuperAdventure_InitializeComponent_West {
            get {
                return ResourceManager.GetString("SuperAdventure_InitializeComponent_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; quest..
        /// </summary>
        internal static string SuperAdventure_MoveTo___quest_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo___quest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  experience points.
        /// </summary>
        internal static string SuperAdventure_MoveTo__experience_points {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo__experience_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  gold.
        /// </summary>
        internal static string SuperAdventure_MoveTo__gold {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo__gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  quest..
        /// </summary>
        internal static string SuperAdventure_MoveTo__quest_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo__quest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to enter this location..
        /// </summary>
        internal static string SuperAdventure_MoveTo__to_enter_this_location_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo__to_enter_this_location_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete it, return with:.
        /// </summary>
        internal static string SuperAdventure_MoveTo_To_complete_it__return_with_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_To_complete_it__return_with_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You complete the &apos;.
        /// </summary>
        internal static string SuperAdventure_MoveTo_You_complete_the__ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_You_complete_the__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a .
        /// </summary>
        internal static string SuperAdventure_MoveTo_You_must_have_a_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_You_must_have_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive: .
        /// </summary>
        internal static string SuperAdventure_MoveTo_You_receive__ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_You_receive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive the .
        /// </summary>
        internal static string SuperAdventure_MoveTo_You_receive_the_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_You_receive_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You see a .
        /// </summary>
        internal static string SuperAdventure_MoveTo_You_see_a_ {
            get {
                return ResourceManager.GetString("SuperAdventure_MoveTo_You_see_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SuperAdventure_UpdateInventoryListInUI_Name {
            get {
                return ResourceManager.GetString("SuperAdventure_UpdateInventoryListInUI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string SuperAdventure_UpdateInventoryListInUI_Quantity {
            get {
                return ResourceManager.GetString("SuperAdventure_UpdateInventoryListInUI_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done?.
        /// </summary>
        internal static string SuperAdventure_UpdateQuestListInUI_Done_ {
            get {
                return ResourceManager.GetString("SuperAdventure_UpdateQuestListInUI_Done_", resourceCulture);
            }
        }
    }
}
